VD music(VD)
{
	print("\nDo ");
	tune("T120 C4e");
	print("I ");
	tune("T120 D4e");
	print("ha");
	tune("T120 E4h");
	print("ve an ");
	tune("T120 D4e"); 
	print("ide");
	tune("T120 E4e G4q");
	print("a?\n");
	tune("T120 A4h");
	tune("T120 Rq");
	print("I");
	tune("T120 G4h");
	print("s i");
	tune("T120 F4h");
	print("t a ");
	tune("T120 E4q");
	print("spa");
	tune("T120 C4w");
	print("rk?\n");

	tune("T120 Rq");

	print("Do ");
	tune("T120 C4e");
	print("I ");
	tune("T120 D4e");
	print("ha");
	tune("T120 E4h");
	print("ve an ");
	tune("T120 D4e"); 
	print("ide");
	tune("T120 E4e G4q");
	print("a?\n");
	tune("T120 A4h");
	tune("T120 Rq");
	print("I");
	tune("T120 E4h");
	print("t i");
	tune("T120 G4h");
	print("s a ");
	tune("T120 A4q");
	print("spa");
	tune("T120 C5w");
	print("rk!\n");

	tune("T120 Rq");

	print("Is ");
	tune("T120 E4e");
	print("it ");
	tune("T120 F4e");
	print("re");
	tune("T120 G4q"); 
	print("ady ");
	tune("T120 A4h");
	print("for ");
	tune("T120 G4e");
	print("cre");
	tune("T120 F4e");
	print("a");
	tune("T120 E4q");
	print("tion?\n");
	tune("T120 Rq G4q");
	print("Le");
	tune("T120 A4h");
	print("t it ");
	tune("T120 C5w Rq");
	print("be ");
	tune("T120 C5h");
	print("do");
	tune("T120 B4h");
	print("ne!\n");
	tune("T120 A4w");

	tune("T120 Rq");

	print("Is ");
	tune("T120 E4e");
	print("it ");
	tune("T120 F4e");
	print("re");
	tune("T120 G4q"); 
	print("ady ");
	tune("T120 A4h");
	print("for ");
	tune("T120 G4e");
	print("cre");
	tune("T120 Rq F4e");
	print("a");
	tune("T120 E4q");
	print("tion?\n");
	tune("T120 G4q");
	print("Le");
	tune("T120 A4h");
	print("t it ");
	tune("T120 C5w Rq");
	print("be ");
	tune("T120 C5h");
	print("do");
	tune("T120 B4h");
	print("ne!\n");
	tune("T120 A4w");

	tune("T120 Rq");

	print("Make ");
	tune("T120 E4e");
	print("it ");
	tune("T120 F4e");
	print("re");
	tune("T120 G4q"); 
	print("ady ");
	tune("T120 A4h");
	print("for ");
	tune("T120 G4e");
	print("cre");
	tune("T120 F4e");
	print("a");
	tune("T120 E4q");
	print("tion.\n");
	tune("T120 G4q Rq");
	print("It ");
	tune("T120 A4h");
	print("is ");
	tune("T120 C5w Rq");
	print("a ");
	tune("T120 A4h");
	print("spa");
	tune("T120 B4h");
	print("r");
	tune("T120 C5h");
	print("k!\n\n");
	tune("T120 C5w");
}

INT main(VD)
{
	cls;
	music();
	mm;
	return 0;
}


